name: Build thesis
on:
  push:
    branches: [main]
    paths:
      - "docs/paper/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
          working_directory: docs/paper

      - name: Upload to artifactory
        uses: ./.github/actions/artifactory_upload
        with:
          input_file_path: docs/paper/thesis.pdf
          storage_path: dim/thesis/latest.pdf
          username:  ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_GENERIC_TOKEN }}
