name: Docker build debian-10
on:
  push:
    branches: [main]
    paths:
      - "dockerfiles/build_images/debian-10/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dockerfiles/build_images/debian-10/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/diploma:debian-10

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
