name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rurabori/diploma:ubuntu-20.04

    env:
      CXX: clang++-12
      CC: clang-12
      CUDACXX: /usr/local/cuda/bin/nvcc
      CONAN_USER_HOME: ${{github.workspace}}

    steps:
      - uses: actions/checkout@v2

      # TODO: switch this to conan presets + cmakepresets eventually.
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ${{ env.CONAN_USER_HOME }}/.conan
          key: ${{ runner.os }}-${{ hashFiles('conanfile.py') }}-${{ env.BUILD_TYPE }}-${{ env.CC }}-${{ env.CXX }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CUDA_ARCHITECTURES=75 -DCMAKE_CUDA_STANDARD=20 -DCMAKE_CXX_CLANG_TIDY="clang-tidy-12" -G "Ninja"
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build
