name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: rurabori/diploma:ubuntu-20.04
            cc: clang-12
            cxx: clang++-12
            pkg_config_path: "" # empty for now, if we make ubuntu builds of PETSc we might need this.
            additional_cmake_options: -DCMAKE_CXX_CLANG_TIDY="clang-tidy-12"
            artifact_name: ubuntu-20.04

          - image: rurabori/diploma:debian-10
            cc: clang-12
            cxx: clang++-12
            pkg_config_path: /usr/lib/petsc/lib/pkgconfig
            additional_cmake_options: -DCMAKE_TOOLCHAIN_FILE="cmake/toolchains/debian-10-llvm-12-libcpp.cmake"
            artifact_name: debian-10

    runs-on: ubuntu-latest
    container:
      image: ${{matrix.image}}

    env:
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}
      CUDACXX: /usr/local/cuda/bin/nvcc
      CONAN_USER_HOME: ${{github.workspace}}
      PKG_CONFIG_PATH: ${{matrix.pkg_config_path}}

    steps:
      - uses: actions/checkout@v2

      # TODO: switch this to conan presets + cmakepresets eventually.
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ${{ env.CONAN_USER_HOME }}/.conan
          key: ${{matrix.image}}-${{ runner.os }}-${{ hashFiles('conanfile.py') }}-${{ env.BUILD_TYPE }}-${{ env.CC }}-${{ env.CXX }}-20

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Denable_cuda_backend="OFF" -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install"  ${{matrix.additional_cmake_options}}  -G "Ninja"

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build

      - name: Install
        run: cmake --build ${{github.workspace}}/build --target install

      - name: Move artifacts
        run: mv ${{github.workspace}}/install install

      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.artifact_name}}
          path: install
